export const INDIAN_STATES: string[] = [
  "Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat",
  "Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh",
  "Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab",
  "Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh",
  "Uttarakhand","West Bengal",
  "Andaman and Nicobar Islands","Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu","Delhi",
  "Jammu and Kashmir","Ladakh","Lakshadweep","Puducherry",
];

export const INDIA_DISTRICTS: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Anantapur","Bapatla","Chittoor","East Godavari","Eluru","Guntur","Kadapa","Kakinada",
    "Konaseema","Krishna","Kurnool","Nandyal","Nellore","NTR","Palnadu","Parvathipuram Manyam",
    "Prakasam","Sri Potti Sriramulu Nellore","Sri Sathya Sai","Srikakulam","Tirupati",
    "Visakhapatnam","Vizianagaram","West Godavari","YSR Kadapa",
    "Vijayawada","Rajamahendravaram","Rajahmundry","Ongole","Bhimavaram",
  ],
  "Arunachal Pradesh": [
    "Anjaw","Changlang","East Kameng","East Siang","Kamle","Kra Daadi","Kurung Kumey",
    "Lepa Rada","Lohit","Longding","Lower Dibang Valley","Lower Siang","Lower Subansiri",
    "Namsai","Pakke Kessang","Papum Pare","Shi Yomi","Siang","Tawang","Tirap",
    "Upper Dibang Valley","Upper Siang","Upper Subansiri","West Kameng","West Siang",
    "Itanagar","Bomdila","Ziro","Along","Pasighat","Tezu",
  ],
  "Assam": [
    "Bajali","Baksa","Barpeta","Biswanath","Bongaigaon","Cachar","Charaideo","Chirang",
    "Darrang","Dhemaji","Dhubri","Dibrugarh","Dima Hasao","Goalpara","Golaghat","Hailakandi",
    "Hojai","Jorhat","Kamrup Metropolitan","Kamrup","Karbi Anglong","Karimganj","Kokrajhar",
    "Lakhimpur","Majuli","Morigaon","Nagaon","Nalbari","Sivasagar","Sonitpur","South Salmara-Mankachar",
    "Tamulpur","Tinsukia","Udalguri","West Karbi Anglong",
    "Guwahati","Silchar","Jorhat","Dibrugarh","Tezpur",
  ],
  "Bihar": [
    "Araria","Arwal","Aurangabad","Banka","Begusarai","Bhagalpur","Bhojpur","Buxar",
    "Darbhanga","East Champaran","Gaya","Gopalganj","Jamui","Jehanabad","Kaimur","Katihar",
    "Khagaria","Kishanganj","Lakhisarai","Madhepura","Madhubani","Munger","Muzaffarpur",
    "Nalanda","Nawada","Patna","Purnia","Rohtas","Saharsa","Samastipur","Saran","Sheikhpura",
    "Sheohar","Sitamarhi","Siwan","Supaul","Vaishali","West Champaran",
    "Gaya","Bhagalpur","Darbhanga","Arrah","Begusarai","Katihar",
  ],
  "Chhattisgarh": [
    "Balod","Baloda Bazar","Balrampur","Bastar","Bemetara","Bijapur","Bilaspur","Dantewada",
    "Dhamtari","Durg","Gariaband","Gaurela-Pendra-Marwahi","Janjgir-Champa","Jashpur",
    "Kabirdham","Kanker","Kondagaon","Korba","Koriya","Mahasamund","Mungeli","Narayanpur",
    "Raigarh","Raipur","Rajnandgaon","Sukma","Surajpur","Surguja",
    "Bhilai","Bilaspur","Korba","Durg","Jagdalpur","Ambikapur",
  ],
  "Goa": [
    "North Goa","South Goa",
    "Panaji","Margao","Vasco da Gama","Mapusa","Ponda","Bicholim","Sanquelim","Mormugao",
  ],
  "Gujarat": [
    "Ahmedabad","Amreli","Anand","Aravalli","Banaskantha","Bharuch","Bhavnagar","Botad",
    "Chhota Udaipur","Dahod","Dang","Devbhoomi Dwarka","Gandhinagar","Gir Somnath",
    "Jamnagar","Junagadh","Kheda","Kutch","Mahisagar","Mehsana","Morbi","Narmada",
    "Navsari","Panchmahal","Patan","Porbandar","Rajkot","Sabarkantha","Surat","Surendranagar",
    "Tapi","Vadodara","Valsad",
    "Surat","Vadodara","Rajkot","Bhavnagar","Jamnagar","Anand","Gandhinagar",
  ],
  "Haryana": [
    "Ambala","Bhiwani","Charkhi Dadri","Faridabad","Fatehabad","Gurugram","Hisar",
    "Jhajjar","Jind","Kaithal","Karnal","Kurukshetra","Mahendragarh","Mewat (Nuh)",
    "Palwal","Panchkula","Panipat","Rewari","Rohtak","Sirsa","Sonipat","Yamunanagar",
    "Gurugram","Faridabad","Rohtak","Ambala","Hisar","Karnal","Panipat","Sonipat",
  ],
  "Himachal Pradesh": [
    "Bilaspur","Chamba","Hamirpur","Kangra","Kinnaur","Kullu","Lahaul and Spiti",
    "Mandi","Shimla","Sirmaur","Solan","Una",
    "Shimla","Dharamshala","Mandi","Solan","Palampur","Nahan","Kullu","Manali","Hamirpur",
  ],
  "Jharkhand": [
    "Bokaro","Chatra","Deoghar","Dhanbad","Dumka","East Singhbhum","Garhwa","Giridih",
    "Godda","Gumla","Hazaribagh","Jamtara","Khunti","Koderma","Latehar","Lohardaga",
    "Pakur","Palamu","Ramgarh","Ranchi","Sahebganj","Seraikela Kharsawan","Simdega",
    "West Singhbhum",
    "Ranchi","Jamshedpur","Dhanbad","Bokaro","Hazaribagh","Deoghar","Giridih",
  ],
  "Karnataka": [
    "Bagalkot","Ballari","Belagavi","Bengaluru Rural","Bengaluru Urban","Bidar","Chamarajanagar",
    "Chikkaballapur","Chikkamagaluru","Chitradurga","Dakshina Kannada","Davanagere","Dharwad",
    "Gadag","Hassan","Haveri","Kalaburagi","Kodagu","Kolar","Koppal","Mandya","Mysuru",
    "Raichur","Ramanagara","Shimoga","Tumakuru","Udupi","Uttara Kannada","Vijayapura",
    "Yadgiri",
    "Bengaluru","Mysuru","Hubballi","Mangaluru","Belagavi","Kalaburagi","Davanagere",
    "Shivamogga","Tumakuru","Vijayapura","Dharwad","Udupi","Hassan","Mandya",
  ],
  "Kerala": [
    "Alappuzha","Ernakulam","Idukki","Kannur","Kasaragod","Kollam","Kottayam",
    "Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur",
    "Wayanad",
    "Kochi","Thiruvananthapuram","Kozhikode","Thrissur","Kollam","Palakkad","Alappuzha",
    "Kannur","Kasaragod","Kottayam","Idukki","Wayanad","Pathanamthitta","Malappuram",
  ],
  "Madhya Pradesh": [
    "Agar Malwa","Alirajpur","Anuppur","Ashoknagar","Balaghat","Barwani","Betul","Bhind",
    "Bhopal","Burhanpur","Chhatarpur","Chhindwara","Damoh","Datia","Dewas","Dhar","Dindori",
    "Guna","Gwalior","Harda","Hoshangabad","Indore","Jabalpur","Jhabua","Katni","Khandwa",
    "Khargone","Mandla","Mandsaur","Morena","Narsinghpur","Neemuch","Niwari","Panna",
    "Raisen","Rajgarh","Ratlam","Rewa","Sagar","Satna","Sehore","Seoni","Shahdol",
    "Shajapur","Sheopur","Shivpuri","Sidhi","Singrauli","Tikamgarh","Ujjain","Umaria",
    "Vidisha",
    "Indore","Bhopal","Jabalpur","Gwalior","Ujjain","Sagar","Rewa","Satna","Dewas","Ratlam",
  ],
  "Maharashtra": [
    "Ahmednagar","Akola","Amravati","Aurangabad (Chhatrapati Sambhajinagar)","Beed","Bhandara",
    "Buldhana","Chandrapur","Dhule","Gadchiroli","Gondia","Hingoli","Jalgaon","Jalna",
    "Kolhapur","Latur","Mumbai City","Mumbai Suburban","Nagpur","Nanded","Nandurbar",
    "Nashik","Osmanabad (Dharashiv)","Palghar","Parbhani","Pune","Raigad","Ratnagiri",
    "Sangli","Satara","Sindhudurg","Solapur","Thane","Wardha","Washim","Yavatmal",
    "Mumbai","Pune","Nagpur","Thane","Nashik","Aurangabad","Solapur","Amravati","Kolhapur",
    "Sangli","Satara","Latur","Ahmednagar","Jalgaon","Akola","Nanded","Raigad","Ratnagiri",
  ],
  "Manipur": [
    "Bishnupur","Chandel","Churachandpur","Imphal East","Imphal West","Jiribam","Kakching",
    "Kamjong","Kangpokpi","Noney","Pherzawl","Senapati","Tamenglong","Tengnoupal",
    "Thoubal","Ukhrul",
    "Imphal","Churachandpur","Bishnupur","Thoubal","Senapati","Ukhrul","Jiribam",
  ],
  "Meghalaya": [
    "East Garo Hills","East Jaintia Hills","East Khasi Hills","Eastern West Khasi Hills",
    "North Garo Hills","Ri Bhoi","South Garo Hills","South West Garo Hills",
    "South West Khasi Hills","West Garo Hills","West Jaintia Hills","West Khasi Hills",
    "Shillong","Tura","Nongstoin","Baghmara","Jowai","Williamnagar",
  ],
  "Mizoram": [
    "Aizawl","Champhai","Hnahthial","Khawzawl","Kolasib","Lawngtlai","Lunglei","Mamit",
    "Saitual","Serchhip","Siaha",
    "Aizawl","Lunglei","Champhai","Serchhip","Kolasib","Mamit","Siaha","Lawngtlai",
  ],
  "Nagaland": [
    "Chumoukedima","Dimapur","Kiphire","Kohima","Longleng","Mokokchung","Mon","Niuland",
    "Noklak","Peren","Phek","Shamator","Tseminyu","Tuensang","Wokha","Zunheboto",
    "Kohima","Dimapur","Mokokchung","Tuensang","Wokha","Zunheboto","Mon","Phek",
  ],
  "Odisha": [
    "Angul","Balangir","Balasore","Bargarh","Bhadrak","Boudh","Cuttack","Deogarh",
    "Dhenkanal","Gajapati","Ganjam","Jagatsinghapur","Jajpur","Jharsuguda","Kalahandi",
    "Kandhamal","Kendrapara","Kendujhar","Khordha","Koraput","Malkangiri","Mayurbhanj",
    "Nabarangpur","Nayagarh","Nuapada","Puri","Rayagada","Sambalpur","Subarnapur",
    "Sundargarh",
    "Bhubaneswar","Cuttack","Rourkela","Berhampur","Sambalpur","Puri","Balasore",
    "Bhadrak","Baripada","Jharsuguda","Bargarh","Koraput","Rayagada",
  ],
  "Punjab": [
    "Amritsar","Barnala","Bathinda","Faridkot","Fatehgarh Sahib","Fazilka","Ferozepur",
    "Gurdaspur","Hoshiarpur","Jalandhar","Kapurthala","Ludhiana","Malerkotla","Mansa",
    "Moga","Mohali (SAS Nagar)","Muktsar","Nawanshahr","Pathankot","Patiala","Rupnagar",
    "Sangrur","Shaheed Bhagat Singh Nagar","Tarn Taran",
    "Ludhiana","Amritsar","Jalandhar","Patiala","Bathinda","Hoshiarpur","Mohali",
    "Ferozepur","Gurdaspur","Fatehgarh Sahib","Sangrur","Faridkot","Muktsar","Mansa",
  ],
  "Rajasthan": [
    "Ajmer","Alwar","Banswara","Baran","Barmer","Bharatpur","Bhilwara","Bikaner","Bundi",
    "Chittorgarh","Churu","Dausa","Dholpur","Dungarpur","Hanumangarh","Jaipur","Jaisalmer",
    "Jalore","Jhalawar","Jhunjhunu","Jodhpur","Karauli","Kota","Nagaur","Pali","Pratapgarh",
    "Rajsamand","Sawai Madhopur","Sikar","Sirohi","Sri Ganganagar","Tonk","Udaipur",
    "Jaipur","Jodhpur","Udaipur","Kota","Ajmer","Bikaner","Alwar","Bharatpur","Sikar",
    "Pali","Nagaur","Jhunjhunu","Churu","Bhilwara","Barmer","Jaisalmer","Jalore","Bundi",
  ],
  "Sikkim": [
    "East Sikkim","North Sikkim","Pakyong","Soreng","South Sikkim","West Sikkim",
    "Gangtok","Namchi","Mangan","Gyalshing","Jorethang","Singtam",
  ],
  "Tamil Nadu": [
    "Ariyalur","Chengalpattu","Chennai","Coimbatore","Cuddalore","Dharmapuri","Dindigul",
    "Erode","Kallakurichi","Kanchipuram","Kanyakumari","Karur","Krishnagiri","Madurai",
    "Mayiladuthurai","Nagapattinam","Namakkal","Nilgiris","Perambalur","Pudukkottai",
    "Ramanathapuram","Ranipet","Salem","Sivaganga","Tenkasi","Thanjavur","Theni",
    "Thoothukudi","Tiruchirappalli","Tirunelveli","Tirupathur","Tiruppur","Tiruvallur",
    "Tiruvannamalai","Tiruvarur","Vellore","Villupuram","Virudhunagar",
    "Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Tirunelveli","Tiruppur",
    "Vellore","Erode","Thoothukudi","Dindigul","Thanjavur","Krishnagiri","Dharmapuri",
  ],
  "Telangana": [
    "Adilabad","Bhadradri Kothagudem","Hanamkonda","Hyderabad","Jagtial","Jangaon",
    "Jayashankar Bhupalpally","Jogulamba Gadwal","Kamareddy","Karimnagar","Khammam",
    "Komaram Bheem Asifabad","Mahabubabad","Mahbubnagar","Mancherial","Medak",
    "Medchal-Malkajgiri","Mulugu","Nagarkurnool","Nalgonda","Narayanpet","Nirmal",
    "Nizamabad","Peddapalli","Rajanna Sircilla","Rangareddy","Sangareddy","Siddipet",
    "Suryapet","Vikarabad","Wanaparthy","Warangal","Yadadri Bhuvanagiri",
    "Hyderabad","Warangal","Nizamabad","Karimnagar","Khammam","Ramagundam","Mahbubnagar",
    "Nalgonda","Adilabad","Suryapet","Siddipet","Jagtial","Medak","Rangareddy",
  ],
  "Tripura": [
    "Dhalai","Gomati","Khowai","North Tripura","Sepahijala","South Tripura","Sipahijala",
    "Unakoti","West Tripura",
    "Agartala","Dharmanagar","Udaipur","Kailashahar","Belonia","Ambassa","Khowai",
  ],
  "Uttar Pradesh": [
    "Agra","Aligarh","Ambedkar Nagar","Amethi","Amroha","Auraiya","Ayodhya","Azamgarh",
    "Baghpat","Bahraich","Ballia","Balrampur","Banda","Barabanki","Bareilly","Basti",
    "Bhadohi","Bijnor","Budaun","Bulandshahr","Chandauli","Chitrakoot","Deoria","Etah",
    "Etawah","Farrukhabad","Fatehpur","Firozabad","Gautam Buddha Nagar","Ghaziabad",
    "Ghazipur","Gonda","Gorakhpur","Hamirpur","Hapur","Hardoi","Hathras","Jalaun",
    "Jaunpur","Jhansi","Kannauj","Kanpur Dehat","Kanpur Nagar","Kasganj","Kaushambi",
    "Kushinagar","Lakhimpur Kheri","Lalitpur","Lucknow","Maharajganj","Mahoba","Mainpuri",
    "Mathura","Mau","Meerut","Mirzapur","Moradabad","Muzaffarnagar","Pilibhit","Pratapgarh",
    "Prayagraj","Rae Bareli","Rampur","Saharanpur","Sambhal","Sant Kabir Nagar",
    "Sant Ravidas Nagar","Shahjahanpur","Shamli","Shravasti","Siddharthnagar","Sitapur",
    "Sonbhadra","Sultanpur","Unnao","Varanasi",
    "Lucknow","Kanpur","Ghaziabad","Agra","Varanasi","Meerut","Prayagraj","Bareilly",
    "Aligarh","Moradabad","Gorakhpur","Saharanpur","Jhansi","Mathura","Muzaffarnagar",
    "Noida","Faizabad","Firozabad","Rampur","Hapur","Etawah","Mirzapur","Bulandshahr",
  ],
  "Uttarakhand": [
    "Almora","Bageshwar","Chamoli","Champawat","Dehradun","Haridwar","Nainital","Pauri Garhwal",
    "Pithoragarh","Rudraprayag","Tehri Garhwal","Udham Singh Nagar","Uttarkashi",
    "Dehradun","Haridwar","Roorkee","Haldwani","Rudrapur","Kashipur","Rishikesh","Almora",
    "Nainital","Pithoragarh","Mussoorie","Kotdwar","Ramnagar","Srinagar (Garhwal)",
  ],
  "West Bengal": [
    "Alipurduar","Bankura","Birbhum","Cooch Behar","Dakshin Dinajpur","Darjeeling",
    "Hooghly","Howrah","Jalpaiguri","Jhargram","Kalimpong","Kolkata","Malda","Murshidabad",
    "Nadia","North 24 Parganas","Paschim Bardhaman","Paschim Medinipur","Purba Bardhaman",
    "Purba Medinipur","Purulia","South 24 Parganas","Uttar Dinajpur",
    "Kolkata","Howrah","Asansol","Siliguri","Durgapur","Bardhaman","Malda","Baharampur",
    "Kharagpur","Haldia","Darjeeling","Jalpaiguri","Cooch Behar","Krishnanagar","Birbhum",
  ],
  "Andaman and Nicobar Islands": [
    "Nicobar","North and Middle Andaman","South Andaman",
    "Port Blair","Diglipur","Car Nicobar","Rangat","Mayabunder","Campbell Bay",
  ],
  "Chandigarh": [
    "Chandigarh",
    "Sector 1","Sector 2","Sector 3","Sector 4","Sector 5","Sector 6","Sector 7","Sector 8",
    "Sector 9","Sector 10","Sector 11","Sector 12","Sector 14","Sector 15","Sector 16",
    "Sector 17","Sector 18","Sector 19","Sector 20","Sector 21","Sector 22","Sector 23",
    "Sector 24","Sector 25","Sector 26","Sector 27","Sector 28","Sector 29","Sector 30",
    "Sector 31","Sector 32","Sector 33","Sector 34","Sector 35","Sector 36","Sector 37",
    "Sector 38","Sector 39","Sector 40","Sector 41","Sector 42","Sector 43","Sector 44",
    "Sector 45","Sector 46","Sector 47","Sector 48","Sector 49","Sector 50","Mani Majra",
    "Burail","Dhanas","Maloya","Kajheri","Behlana",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Dadra and Nagar Haveli","Daman","Diu",
    "Silvassa","Daman","Diu","Amli","Khanvel","Naroli",
  ],
  "Delhi": [
    "Central Delhi","East Delhi","New Delhi","North Delhi","North East Delhi",
    "North West Delhi","Shahdara","South Delhi","South East Delhi","South West Delhi",
    "West Delhi",
    "Connaught Place","Karol Bagh","Lajpat Nagar","Nehru Place","Rohini","Dwarka",
    "Janakpuri","Pitampura","Saket","Vasant Kunj","Mayur Vihar","Preet Vihar",
    "Vikaspuri","Uttam Nagar","Paschim Vihar","Shalimar Bagh","Ashok Vihar",
    "Model Town","Civil Lines","Kamla Nagar","Mukherjee Nagar","Rajouri Garden",
    "Tilak Nagar","Hari Nagar","Krishna Nagar","Laxmi Nagar","Patparganj",
    "Noida Extension (Delhi NCR)","Greater Noida (Delhi NCR)",
  ],
  "Jammu and Kashmir": [
    "Anantnag","Bandipora","Baramulla","Budgam","Doda","Ganderbal","Jammu","Kathua",
    "Kishtwar","Kulgam","Kupwara","Poonch","Pulwama","Rajouri","Ramban","Reasi",
    "Samba","Shopian","Srinagar","Udhampur",
    "Srinagar","Jammu","Anantnag","Baramulla","Budgam","Pulwama","Kupwara","Kathua",
    "Udhampur","Reasi","Ramban","Kishtwar","Doda","Rajouri","Poonch",
  ],
  "Ladakh": [
    "Kargil","Leh",
    "Leh","Kargil","Nubra","Zanskar","Diskit","Padum","Khalsi",
  ],
  "Lakshadweep": [
    "Lakshadweep",
    "Kavaratti","Agatti","Amini","Andrott","Kalpeni","Kadmat","Kiltan","Chetlat","Bitra",
    "Minicoy",
  ],
  "Puducherry": [
    "Karaikal","Mahe","Puducherry","Yanam",
    "Puducherry","Karaikal","Oulgaret","Villianur","Ariyankuppam","Nettapakkam",
  ],
};
